### ISSUE TITLE
Hello, woroniecki. I'm honour to read your code.  May i ask a question : why are there two distance(distance and realDistance) in your edge class? What's the meaning of these two distance?

### ISSUE THREAD

**Issue by alance123** [woroniecki/PathingLib#1]

**Comment by woroniecki** [comment]
Sorry for late answer. I haven't noticed this question. Variable distance is used inside algorithm but total distance is calculated by distance variable. It's for case where we prioritize some edges more than others for example: best path for cyclist in this case we set in cycle edges distance to be shorter of some x% than real, result path will be directed to go thru more cyclist paths instead of just find the shortest path.
